name: IndexNow Submitter

permissions: 
  contents: write

on:
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # ensures full history so we can push commits
          persist-credentials: true # use the provided token for git push
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
    
      - name: Run IndexNow script
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          # If using a custom key file URL, uncomment:
          # KEY_LOCATION: ${{ secrets.KEY_LOCATION }}
          # If overriding the sitemap URL, uncomment:
          # SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
        run: |
          python submit_indexnow.py
    
      - name: Commit state updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f submitted_urls.json deleted_urls.json
          # Commit and push only if files changed
          git diff --cached --quiet || (
            git commit -m "chore: update IndexNow state files" &&
            git push
          )