name: "IndexNow Submitter"

on: 
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run IndexNow script
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          # If using a custom key file URL, set this secret too:
          # KEY_LOCATION: ${{ secrets.KEY_LOCATION }}
          # To override the default sitemap, set this secret:
          # SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
        run: |
          python submit_indexnow.py

      - name: Commit state updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submitted_urls.json deleted_urls.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update IndexNow state files"
            git push
          else
            echo "No changes to state files"
          fi